"""special price column name change

Revision ID: 74e1f8b4840c
Revises: 3680eaf990b6
Create Date: 2023-12-27 03:09:42.198418

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '74e1f8b4840c'
down_revision = '3680eaf990b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_list_special_price', table_name='price_list')
    op.execute('ALTER TABLE public.price_list RENAME COLUMN special_price TO price;')
    op.create_index(op.f('ix_price_list_price'), 'price_list', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('products_id_seq'::regclass)"))
    op.drop_index(op.f('ix_price_list_price'), table_name='price_list')
    op.create_index('ix_price_list_special_price', 'price_list', ['price'], unique=False)
    # ### end Alembic commands ###
